from pydantic import BaseModel
from typing import Optional, List


# ---------- Request ----------
class RecommendRequest(BaseModel):
    mood: str
    location: str
    budget: Optional[str] = None
    time: Optional[str] = None


# ---------- AI Plan (Generated by DeepSeek) ----------
class AIPlan(BaseModel):
    intent: str
    place_types: List[str]
    vibe: List[str]
    avoid: List[str]
    ideal_time: Optional[str]
    reasoning: str


# ---------- Recommended Place ----------
class Place(BaseModel):
    name: str
    rating: Optional[float] = None
    address: Optional[str] = None
    reason: str


# ---------- Final Response ----------
class RecommendResponse(BaseModel):
    plan: AIPlan
    recommendations: List[Place]
